### ISSUE TITLE
Wrong Download Error

### ISSUE THREAD

**Issue by Ariana** [petercunha/Wizardli#2]
So, I found an issue where if two users are using the site at the same time and one queues a download but does not download it and closes the page and another user goes to download a video they will get the mp3 the previous user put in, I have tested this with multiple other people and successfully recreated it every time.

**Comment by petercunha** [comment]
@Ariana thank you for spotting this weird bug! I'll try to figure it out and implement a fix soon.

**Comment by petercunha** [comment]
Thanks again for finding this, should be fixed in commit `a4d12d12aa0130dff8ab31c5f188b7ea92201825`. I'll be pushing the fix to production soon.
